name: dart_intl_search
description: |
  Extension for a String comparison with a localization transcription (BE, ZH, etc.)
version: 1.2.2
homepage: https://github.com/lyskouski/dart_intl_search
repository: https://github.com/lyskouski/dart_intl_search
issue_tracker: https://github.com/lyskouski/dart_intl_search/issues
environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
