// Copyright 2023 The terCAD team. All rights reserved.
// Use of this source code is governed by a MIT license
// that can be found in the LICENSE file.

const normalizeChars = {
  'Š': 'S',
  'š': 's',
  'Ð': 'Dj',
  'Ž': 'Z',
  'ž': 'z',
  'À': 'A',
  'Á': 'A',
  'Â': 'A',
  'Ã': 'A',
  'Ä': 'A',
  'Å': 'A',
  'Æ': 'A',
  'Ç': 'C',
  'È': 'E',
  'É': 'E',
  'Ê': 'E',
  'Ë': 'E',
  'Ì': 'I',
  'Í': 'I',
  'Î': 'I',
  'Ï': 'I',
  'Ñ': 'N',
  'Ń': 'N',
  'Ò': 'O',
  'Ó': 'O',
  'Ô': 'O',
  'Õ': 'O',
  'Ö': 'O',
  'Ø': 'O',
  'Ù': 'U',
  'Ú': 'U',
  'Û': 'U',
  'Ü': 'U',
  'Ý': 'Y',
  'Þ': 'B',
  'ß': 'Ss',
  'à': 'a',
  'á': 'a',
  'â': 'a',
  'ã': 'a',
  'ä': 'a',
  'å': 'a',
  'æ': 'a',
  'ç': 'c',
  'è': 'e',
  'é': 'e',
  'ê': 'e',
  'ë': 'e',
  'ì': 'i',
  'í': 'i',
  'î': 'i',
  'ï': 'i',
  'ð': 'o',
  'ñ': 'n',
  'ń': 'n',
  'ò': 'o',
  'ó': 'o',
  'ô': 'o',
  'õ': 'o',
  'ö': 'o',
  'ø': 'o',
  'ù': 'u',
  'ú': 'u',
  'û': 'u',
  'ü': 'u',
  'ý': 'y',
  'þ': 'b',
  'ÿ': 'y',
  'ƒ': 'f',
  'ă': 'a',
  'ș': 's',
  'ț': 't',
  'Ă': 'A',
  'Ș': 'S',
  'Ț': 'T',
};

String basic(String value) {
  for (var e in normalizeChars.entries) {
    value = value.replaceAll(e.key, e.value);
  }
  final result = value.replaceAll(RegExp(r'[^\x00-\x7F]'), '').toLowerCase();
  if (value.isNotEmpty && result.isEmpty) {
    return value.toLowerCase();
  }
  return result;
}
