// Copyright 2023 The terCAD team. All rights reserved.
// Use of this source code is governed by a MIT license
// that can be found in the LICENSE file.

import 'basic.dart';

const hindiToRomanized = {
  "अ": "a",
  "आ": "aa",
  "इ": "i",
  "ई": "ii",
  "उ": "u",
  "ऊ": "uu",
  "ऋ": "r̥",
  "ए": "e",
  "ऐ": "ai",
  "ओ": "o",
  "औ": "au",
  "क": "k",
  "ख": "kh",
  "ग": "g",
  "घ": "gh",
  "ङ": "ṅ",
  "च": "c",
  "छ": "ch",
  "ज": "j",
  "झ": "jh",
  "ञ": "ñ",
  "ट": "ṭ",
  "ठ": "ṭh",
  "ड": "ḍ",
  "ढ": "ḍh",
  "ण": "ṇ",
  "त": "t",
  "थ": "th",
  "द": "d",
  "ध": "dh",
  "न": "n",
  "प": "p",
  "फ": "ph",
  "ब": "b",
  "भ": "bh",
  "म": "m",
  "य": "y",
  "र": "r",
  "ल": "l",
  "व": "v",
  "श": "ś",
  "ष": "ṣ",
  "स": "s",
  "ह": "h",
  "़": "ʾ",
  "ा": "ā",
  "ि": "i",
  "ी": "ī",
  "ु": "u",
  "ू": "ū",
  "ृ": "ṛ",
  "े": "e",
  "ै": "ai",
  "ो": "o",
  "ौ": "au",
  "०": "0",
  "१": "1",
  "२": "2",
  "३": "3",
  "४": "4",
  "५": "5",
  "६": "6",
  "७": "7",
  "८": "8",
  "९": "9",
  "क़": "q",
  "ख़": "x",
  "ग़": "ġ",
  "ज़": "z",
  "ड़": "ṛ̆",
  "ढ़": "ṛ̆h",
  "फ़": "f",
  "ॠ": "ṝ",
  "ॡ": "ḹ",
  "।": "|",
  "॥": "||",
  "ॄ": "ṝ̆",
};

String hiIN(String value) {
  for (var e in hindiToRomanized.entries) {
    value = value.replaceAll(e.key, e.value);
  }
  return basic(value);
}
